# Generated by Django 5.2.1 on 2025-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
