# Generated by Django 5.2.1 on 2025-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='productos.proveedor'),
        ),
    ]
